version: '3.8'

services:
  # ==========================================
  # CONTAINER 1: BANCO DE DADOS POSTGRESQL
  # ==========================================
  db:
    image: postgres:16
    container_name: enzitech_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: enzitech
      POSTGRES_USER: enzitech_user
      POSTGRES_PASSWORD: 9Jt3E1Fc5Kig
    volumes:
      - enzitech_pgdata:/var/lib/postgresql/data
    networks:
      - enzitech_network

  # ==========================================
  # CONTAINER 2: API Spring Boot
  # ==========================================
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enzitech_api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:8082:8080"
    env_file:
      - .env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - enzitech_network
      - enzitech_mail

volumes:
  enzitech_pgdata:

networks:
  enzitech_network:
  enzitech_mail:
    external: true